name: Codecov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cover:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Generate coverage report
        run: go test -cover -covermode=atomic -coverprofile=coverage.txt .
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
